### ISSUE TITLE
Not able to run the app locally

### ISSUE THREAD

**Issue by RameshGhk** [Stranger6667/schemathesis-example#1]
Hi there,
Could anybody take look at my issue please
I used virtual environment.
docker container for postgres db
When I run `python3 -m example` from pycharm I get below error

`  File "/usr/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 5432)
`

**Comment by Stranger6667** [comment]
Hi @RameshGhk !

Did you forward 5432 port from the container to the host machine?

**Comment by RameshGhk** [comment]
@Stranger6667 
Yes, 
Here is the content from compose file

`version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: newPassword`

**Comment by RameshGhk** [comment]
I get new error now

`    await asyncio.wait_for(connected, timeout=timeout)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "tester"
`

**Comment by Stranger6667** [comment]
Please, take a look at this commit - 94fab6f931549628cd994d017c9988359abcad66

I added a sample docker-compose.yml file that creates a configured database (don't forget to remove the previous one first with `docker-compose rm`)

let me know if it solves the issue :) If not, I'd be happy to provide more info

**Comment by RameshGhk** [comment]
@Stranger6667 Thank you very much :)
DB connection is working fine now.

**Comment by Stranger6667** [comment]
Great! Feel free reopen this issue if you encounter any further problems
